SUBROUTINE YAWATT(MJD,CPRN,CSVN,BLK,XSAT,XSUN,XSCF,YSCF,ZSCF)
!!
!*
USE const
IMPLICIT NONE

!*
! THE ARGUMENTS
!!-----------------------------
REAL(RL) :: MJD,XSAT(1:*),XSUN(1:*)
REAL(RL) :: XSCF(1:*),YSCF(1:*),ZSCF(1:*)
CHARACTER(LEN=*) :: CPRN,CSVN,BLK

  !*
  ! THE LOCAL VARIABLES
  !!-----------------------------

  INTEGER(IT), PARAMETER :: MAXECLIP=120
  INTEGER(IT) :: IDIR,NECLIPS(MAXSAT)
  INTEGER(IT) :: I,IPRN,IECLIPS,NPRN,MODE

  REAL(RL) :: MJD0,MJDLAST(MAXSAT),YRATE
  REAL(RL) :: ECLSTM(MAXECLIP,MAXSAT)
  REAL(RL) :: ECLETM(MAXECLIP,MAXSAT)
  REAL(RL) :: RATE(32),SVBCOS,U,YAW,XSCFB(3)
  REAL(RL) :: ANIGHT,BETA,YANGLE,PHI

  LOGICAL(LG) :: LFIRST
  DATA LFIRST /.TRUE./
  CHARACTER(LEN_PRN) :: PRN(MAXSAT)

  DATA RATE /0.1211D0,0.1339D0,0.1230D0,0.1233D0,0.1180D0,0.1266D0,0.1269D0, &
             0.1033D0,0.1278D0,0.0978D0,0.2000D0,0.1990D0,0.2000D0,0.0815D0, &
             0.1303D0,0.0838D0,0.1401D0,0.1069D0,0.0980D0,0.1030D0,0.1366D0, &
             0.1025D0,0.1140D0,0.1089D0,0.1001D0,0.1227D0,0.1194D0,0.1260D0, &
             0.1228D0,0.1165D0,0.0969D0,0.1140D0/

  SAVE NPRN,PRN
  SAVE MJD0,MJDLAST,LFIRST,NECLIPS,ECLSTM,ECLETM

  !*
  ! THE FUNCTION CALLED
  !!--------------------------------
  REAL(RL) DOT
  INTEGER(IT) :: POINTER_STRING

  !*
  ! START THE EXECTUABLE CODES
  !!--------------------------------

  IF (LFIRST .EQ. .TRUE.) THEN
    NPRN=0
    MJD0=MJD
    MJDLAST=MJD
    LFIRST=.FALSE.
    NECLIPS=0
    ECLSTM=0.D0
    ECLETM=0.D0
  END IF

  IPRN=POINTER_STRING(NPRN,PRN,CPRN)
  IF (IPRN .EQ. 0) THEN
    NPRN=NPRN+1
    PRN(NPRN)=CPRN
    IPRN=NPRN
  END IF

  ! DIRECTION OF DATA PROCESSION
  IDIR=1
  IF (MJDLAST(IPRN) .GT. MJD) IDIR=-1
  MJDLAST(IPRN)=MJD

  XSCFB(1:3)=XSCF(1:3)

  MODE=1
  SELECT CASE(TRIM(BLK))
    CASE('BLOCK I','BLOCK II','BLOCK IIA')
      ANIGHT=13.25D0+180.D0
      READ(CPRN(2:3),*) I
      YRATE=RATE(I)
    CASE('BLOCK IIR-A','BLOCK IIR-B','BLOCK IIR-M','BLOCK IIIA')
      MODE=-1
      ANIGHT=13.25D0+180.D0
      YRATE=0.2D0
    CASE('BLOCK IIF')
      ANIGHT=13.25D0+180.D0
      YRATE=0.11D0
    CASE('GLONASS-M','GLONASS-K1')
      ANIGHT=14.2D0+180.D0
      YRATE=0.25D0

    CASE('GALILEO-1')
      ANIGHT=15.0D0+180.D0
      YRATE=0.0D0
    CASE('GALILEO-2')
      ANIGHT=4.1D0+180.D0
      YRATE=0.0D0

    CASE('BEIDOU-2I','BEIDOU-2M')
      ANIGHT=3.0D0+180.D0
      YRATE=0.0D0
      IF (TRIM(CSVN).NE.'017' .AND. TRIM(CSVN).NE.'015' .AND. TRIM(CSVN).NE.'005') RETURN
    ! NO YAW MODEL AVALIABLE FOR OTHER SATELLITES
    CASE('BEIDOU-3I-SECM','BEIDOU-3I-CAST','BEIDOU-3M-SECM','BEIDOU-3M-CAST', &
         'BEIDOU-3IS-SECM','BEIDOU-3IS-CAST','BEIDOU-3MS-SECM','BEIDOU-3MS-CAST', &
         'BEIDOU-3SI-SECM','BEIDOU-3SI-CAST','BEIDOU-3SM-SECM','BEIDOU-3SM-CAST')
      ANIGHT=3.0D0+180.D0
      YRATE=0.0D0
    CASE DEFAULT
      RETURN
  END SELECT

  CALL betau(XSAT,XSUN,BETA,U)

  YAW=DATAN2(-DTAN(BETA),DSIN(U))*RAD2DEG
  IF (BLK(1:9).EQ.'BLOCK IIR' .OR. TRIM(BLK).EQ.'BLOCK IIIA') YAW=DATAN2(DTAN(BETA),-DSIN(U))*RAD2DEG

  SVBCOS=DOT(3,XSAT,XSUN)/(DSQRT(XSAT(1)**2+XSAT(2)**2+XSAT(3)**2)*DSQRT(XSUN(1)**2+XSUN(2)**2+XSUN(3)**2))

  SELECT CASE(TRIM(BLK))
    CASE('GALILEO-1','GALILEO-2', &
         'BEIDOU-2I','BEIDOU-2M','BEIDOU-3I-SECM','BEIDOU-3I-CAST','BEIDOU-3M-SECM','BEIDOU-3M-CAST', &
         'BEIDOU-3IS-SECM','BEIDOU-3IS-CAST','BEIDOU-3MS-SECM','BEIDOU-3MS-CAST', &
         'BEIDOU-3SI-SECM','BEIDOU-3SI-CAST','BEIDOU-3SM-SECM','BEIDOU-3SM-CAST')
      CALL ECLIPS2(IDIR,(MJD-MJD0)*86400.D0,CPRN,BLK,YRATE,SVBCOS,ANIGHT, &
                       IECLIPS,NECLIPS(IPRN),ECLSTM(:,IPRN),ECLETM(:,IPRN), &
                       XSAT(1:3),XSCFB,XSAT(4:6),BETA+PI/2.d0,YANGLE,PHI)
    CASE DEFAULT
      CALL ECLIPS(IDIR,(MJD-MJD0)*86400.D0,CPRN,BLK,YRATE,SVBCOS,ANIGHT, &
                       IECLIPS,NECLIPS(IPRN),ECLSTM(:,IPRN),ECLETM(:,IPRN), &
                       XSAT(1:3),XSCFB,XSAT(4:6),BETA+PI/2.d0,YANGLE,PHI)
  END SELECT

  IF (IECLIPS .NE. 0) THEN
    DO I=1, 3
      XSCF(I)=MODE*XSCFB(I)
    END DO
    CALL CROSS(ZSCF,XSCF,YSCF)
    CALL UNIT_VECTOR(3,YSCF,YSCF,U)
  END IF

  RETURN

END SUBROUTINE




SUBROUTINE ECLIPS( IDIR, TTAG, CPRN, BLK, YRATE, SVBCOS, ANIGHT, &
                   IECLIPS, NECLIPS, ECLSTM, ECLETM, &
                   XSV, SANTXYZ, VSVC, BETA, YANGLE, PHI)
!
!       NAME            ECLIPS (version Dec  2013)
!
!     PURPOSE   DETECT ECLIPSING & YAW ROTATE ECLIP. SATELLITES
!                       (THE INPUT BODY-X UNIT VECTOR - SANTXYZ IS YAW-ROTATED
!                        BY PHI-YANGLE (THE ECL-NOMINAL) YAW ANGLE DIFFERENCE)
!
!       COPYRIGHT       GEODETIC SURVEY DIVISION, 2011.
!                       ALL RIGHTS RESERVED.
!                       ALL TERMS AND CONDITIONS APPLY AS DETAILED IN
!                       " TERMS AND CONDITIONS FOR SOFTWARE "
!
!       CONTACT         kouba@geod.nrcan.gc.ca
!
!       UPDATE HISTORY: Aug. 23, 2011:1996-2008 W. AVERAGES of JPL REPROCESSING
!                                YRATE SOLUTIONS FOR ALL II/IIA CODED IN DATA
!                                STATEMENT, THIS ENABLES REPROCESSING FROM 1996
!                       Sep 26, 2011: 1. Corrected bug causing Block IIF shadow
!                               CROSSING MANEVURE WITH 0.06 DEG/SEC RATE EVEN
!                               FOR BETADG > 8 DEG
!                                     2. CORRECTED/improved IIA RECOVERY logic
! Dec 12, 2013 - start
!                       Dec 18, 2013: 1.corrected IIF night turns (USAF Doc.)
!                                     2.small neg beta IIF and small pos IIA noon turn
!                                    (wrong) directions  for |beta| < 0.9deg
!                                     3. PRN/SVN 23 IIA YBIAS= -0.5 deg up to Feb 2004
!                                     4. All the above changes labeled "C Dec 12, 2013"
! Dec 12, 2013 - end
!
!                      Jan 24, 2014:  NOON RECOVERY CORRECTED IF IIA/IIF's HAVE YBIAS=0
!                                    (NOT APPLICABLE CURRENTLY,POSSIBLE FOR FUTURE IIF?)
!                                    & SMALL IIA/IIF BETA IF STATEMENT SIMPLIFIED
!
!     PARAMETERS        DESCRIPTION
!
!        IDIR           DIRECTION OF PROCESSING (1=FORWARD, -1=BACKWARD)
!        IPRN           SV PRN NUMBER (.LE.32 FOR GPS, .GT.32 FOR GLONASS)
!        TTAG           OBSERVATION EPOCH TIME TAG (EG SEC OF GPS WEEK)
!        SVBCOS         SV BETA ANGLE (BETWEEN SV AND SUN RADIUS) COSINE
!        ANOON          SV BETA ANGLE LIMIT (DEG) FOR A NOON TURN MANEVURE
!        ANIGHT         SV BETA ANGLE LIMIT (DEG) FOR A NIGHT SHADOW CROSSING
!        NECLIPS        NUMBER OF ECLIPSING FOR THE PRN SATELLITE
!        ECLSTM         ECLIPSE START TIME(EG SEC OF GPS WEEK)
!        ECLETM         ECLIPSE END TIME  ( "         "      )
!        IECLIPS        SV ECLIPSING (0=NO,1, 2=YES(1=night, 2=noon))
!        PI             = PI=3.1415926536D0
!        XSV(3)         SV X, Y, Z (m)(ITRF)
!        SANTXYZ        BODY-X UNIT VECTOR (ITRF)
!                       WARNING: THE IIA BODY-X ORIENTATION EXPECTED FOR THE IIR
!                        THE  BODY-X REVERSED FOR IIR (SEE BELOW) & RETURNED
!        VSVC           SV INERTIAL VELOCIRY VECTOR IN ITRF
!        BETA           90 DEG + THE SUN ANGLE WITH ORBITAL PLANE(IN RAD)
!        IBLK           SV BLOCK  1=I, 2=II, 3=IIA, IIR=(4, 5) IIF=6
!
!        INTERNAL PARAMETRS DESCRIPTION
! Dec 12, 2013
!        YBIAS       IIA YAW BIAS= 0.5 deg SINCE NOV95,EXCEPT PRN/SVN23?
!        YANGLE         THE NOMINAL YAW ANGLE
!        PHI            THE ECLIPSING YAW ANGLE
!
! REMARKS:
! SVBCOS, the COS of the angle between the sv radius vector and the sun
! radius vector, (the dot product of the above respective unit vectors),
! SVBCOS is used to test against CNOON=COS(ANOON), if sv is entering
! a noon maneuverer (i.e., SVBCOS > CNOON). The ANOON limit
! (typically < 5.7 deg), is determined within the subroutine and depends
! on the  sv yaw rate (YRATE)and GNSS (GPS or GLONASS).
!
! ANIGHT , the shadow limit is the "input " in the subroutine
! call statement, it can be hard coded as it is constant for a GNSS type,
! e.g.,
! 180.D0+-13.25D0 for GPS (IPRN.GE. 32) and 180.D0+-14.20D0 for
! GLONASS (IPRN.GT.32), resp.). CNIGHT=COS(ANIGHT) is used for testing.
! When SVBCOS < CNIGHT (CNIGHT is negative and close to -1),
! the SV enters, or it is in the shadow.
!
! *********************************************************************
!
USE const
IMPLICIT NONE

!*
! THE ARGUMENTS
!!-----------------------------
INTEGER(IT) IDIR
INTEGER(IT) IECLIPS, NECLIPS

REAL(RL) TTAG, SVBCOS, YRATE
REAL(RL) ECLSTM(*), ECLETM(*)
REAL(RL) ANIGHT
REAL(RL) XSV(*),SANTXYZ(*),VSVC(*)
REAL(RL) BETA, YANGLE, PHI

CHARACTER(LEN=*) CPRN, BLK


  !*
  ! THE LOCAL VARIABLES
  !!-----------------------------
  REAL(RL) TWOHR, HALFHR
  REAL(RL) CNOON, CNIGHT
  REAL(RL) DTTAG, ANOON
  REAL(RL) MURATE, DET, BETADG
  REAL(RL) SANTX, SANTY, v(3),r(3)
  REAL(RL) YAWEND, YBIAS
  INTEGER(IT) J, I

  LOGICAL(LG) NOON, NIGHT

  !*
  ! START THE EXECTUABLE CODES
  !!-----------------------------

  ! Dec 12, 2013
  ! YBIAS=-0.5 FOR IIA (IBLK<4) PRN23 (SVN23 UP TO FEB2004,AFTER  IIR SVN60
  ! AND NOT USED), IIF (IBLK=6)=-0.5, USED FOR SMALL NEG BETA NOON TURNS ONLY!
  YBIAS=0.0D0
  IF ((TRIM(BLK).EQ.'BLOCK I') .OR. (TRIM(BLK).EQ.'BLOCK II') .OR. (TRIM(BLK).EQ.'BLOCK IIA')) YBIAS=0.5D0
  IF (CPRN(1:3).EQ.'G23' .OR. BLK(1:9).EQ.'BLOCK IIF') YBIAS=-0.5D0

  IECLIPS=0
  TWOHR =7200.D0
  HALFHR=1800.D0

  ! compute the noon beta angle limit (beta zero) FOR A NOON TURN from YRATEs
  ! THE ACTUAL SAT ORBIT ANGLE RATE (MURATE) (~0.00836 FOR GPS; ~ 0.00888 GLNS)
  MURATE=DSQRT((VSVC(1)**2+VSVC(2)**2+VSVC(3)**2)/(XSV(1)**2+XSV(2)**2+XSV(3)**2))*RAD2DEG

  ANOON=DATAN(MURATE/YRATE)*RAD2DEG
  CNOON=DCOS(ANOON*DEG2RAD)
  CNIGHT=DCOS(ANIGHT*DEG2RAD)

  NOON=.FALSE.
  NIGHT=.FALSE.
  BETADG=BETA*RAD2DEG-90.d0

  ! GLONASS-M NOON TURN MODE ACORDING TO DILSSNER 2010
  IF ((BLK(1:9).EQ.'GLONASS-M' .OR. BLK(1:10).EQ.'GLONASS-K1') .AND. (DABS(BETADG).LT.ANOON)) THEN

    ! ITERATION FOR YAWEND OF THE GLONASS-M NOON TURN
    YAWEND=75.D0

    DO J=1, 3
      YAWEND=DABS(DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI- &
             DEG2RAD*MURATE*YAWEND/YRATE))*RAD2DEG- &
             DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI+ &
             DEG2RAD*MURATE*YAWEND/YRATE))*RAD2DEG)/2.D0
    END DO
    ! UPDATE ANOON, CNOON FOR NEW GLONASS NOON TURN LIMITS
    ANOON=MURATE*YAWEND/YRATE
    CNOON=DCOS(ANOON*DEG2RAD)
  END IF

  ! BLK IIR'S
  IF (BLK(1:9).EQ.'BLOCK IIR' .OR. TRIM(BLK).EQ.'BLOCK IIIA') THEN
    CNIGHT=DCOS((ANOON+180.D0)*DEG2RAD)
    ! BODY-X U VECTOR REVERSAL FOR IIR ONLY
    DO J=1,3
      SANTXYZ(J)=-SANTXYZ(J)
    END DO
  END IF

  IF (SVBCOS .LT. CNIGHT) THEN
    NIGHT=.TRUE.
  END IF
  IF (SVBCOS .GT. CNOON) THEN
    NOON=.TRUE.
  END IF


  ! IF SV IN NIGHT SHADOW OR NOON TURN DURING FORWARD PASS
  ! STORE START AND END TIME OF YAW MANEUVRE (FOR THE BACKWARD RUN)

  ! YAW ANLGE
  YANGLE=DACOS((SANTXYZ(1)*VSVC(1)+SANTXYZ(2)*VSVC(2)+SANTXYZ(3)*VSVC(3))/ &
                DSQRT(VSVC(1)**2+VSVC(2)**2+VSVC(3)**2))*RAD2DEG

  ! IIR YANGLE has the same sign as beta, II/IIA has the opposite sign
  IF (BETADG.LT.0.d0 .AND. (BLK(1:9).EQ.'BLOCK IIR'  .OR. TRIM(BLK).EQ.'BLOCK IIIA')) YANGLE=-YANGLE
  IF (BETADG.GT.0.d0 .AND. (BLK(1:9).NE.'BLOCK IIR' .AND. TRIM(BLK).NE.'BLOCK IIIA')) YANGLE=-YANGLE

  IF (NIGHT .OR. NOON) THEN
    DET=DSQRT((180.d0-DACOS(SVBCOS)*RAD2DEG)**2-BETADG**2)
    PHI=PI/2.d0
    ! Check if already after a midnight or noon
    IF (NIGHT) THEN
      IF (BLK(1:9).EQ.'BLOCK IIR' .OR. TRIM(BLK).EQ.'BLOCK IIIA') THEN
        IF (DABS(YANGLE) .GT. 90.D0) DET=-DET
        IF (DET .NE. 0.d0) PHI=DATAN2(DTAN(BETADG*DEG2RAD),-DSIN(-DET*DEG2RAD))*RAD2DEG
      ELSE
        ! BLK IIA & GLONASS TOO
        IF (DABS(YANGLE) .LT. 90.d0) DET=-DET
        IF (DET .NE. 0.d0) PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG
      END IF
    END IF

    IF (NOON) THEN
      DET=DSQRT((DACOS(SVBCOS)*180.0/PI)**2-BETADG**2)
      IF (BLK(1:9).EQ.'BLOCK IIR' .OR. TRIM(BLK).EQ.'BLOCK IIIA') THEN
        IF (DABS(YANGLE) .LT. 90.d0) DET=-DET
        IF (DET .NE. 0.d0) PHI=DATAN2(DTAN(BETADG*DEG2RAD),-DSIN(PI-DET*DEG2RAD))*RAD2DEG
      ELSE
        ! BLK IIA & GLONASS !
        IF (DABS(YANGLE) .GT. 90.d0) DET=-DET
        IF (DET .NE. 0.d0) PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI-DET*DEG2RAD))*RAD2DEG
      END IF
    END IF

    ! ONLY FORWARD
    IF (IDIR .GT. 0) THEN

      ! INITIALIZE ECLIPSE START AND TIME TAG ARRAYS

      IF (NECLIPS .EQ. 0) THEN
        NECLIPS=NECLIPS+1
        ECLSTM(NECLIPS)=TTAG+DET/MURATE
        ! IIR MIDNIGHT/NOON TURN or II/IIA NOON TURN START
        ! for IIR/GLONAS NIGHT (turn) only makes sense when BETADG < ANOON!
        ! For IIA it gets here only when NOON is true and that happens  only when BETADG < ANOON!
        YAWEND=DATAN(MURATE/YRATE)*RAD2DEG

        IF (((BLK(1:9).EQ.'BLOCK IIR' .OR. TRIM(BLK).EQ.'BLOCK IIIA').OR.NOON) .AND. DABS(BETADG).LT.YAWEND) THEN
          ! GLONASS
          IF (BLK(1:9).EQ.'GLONASS-M' .OR. BLK(1:10).EQ.'GLONASS-K1') THEN
            ! GLONASS NOON TURN MODE ACORDING TO DILSSNER ET AL 2010
            ECLSTM(NECLIPS)=ECLSTM(NECLIPS)-ANOON/MURATE
            ECLETM(NECLIPS)=ECLSTM(NECLIPS)+2.D0*ANOON/MURATE
          ELSE
            ! GPS IIA/IIR/IIF NOON OR IIR MIDNIGHT TURNs
            ECLSTM(NECLIPS)=ECLSTM(NECLIPS)-DABS(BETADG)*DSQRT(ANOON/DABS(BETADG)-1.D0)/MURATE
            ECLETM(NECLIPS)=ECLSTM(NECLIPS)+2.D0*DABS(BETADG)*DSQRT(ANOON/DABS(BETADG)-1.D0)/MURATE
          END IF
        END IF

        ! II/IIA SHADOW START & END TIMES
        IF (((TRIM(BLK).EQ.'BLOCK I').OR.(TRIM(BLK).EQ.'BLOCK II').OR.(TRIM(BLK).EQ.'BLOCK IIA').OR. &
             (TRIM(BLK).EQ.'BLOCK IIF').OR.(TRIM(BLK).EQ.'GLONASS-M').OR.(TRIM(BLK).EQ.'GLONASS-K1')) .AND. NIGHT) THEN
          ECLSTM(NECLIPS)=ECLSTM(NECLIPS)-DSQRT((ANIGHT-180.d0)**2-BETADG**2)/MURATE
          ECLETM(NECLIPS)=ECLSTM(NECLIPS)+2.D0*DSQRT((ANIGHT-180.d0)**2-BETADG**2)/MURATE
        END IF
      END IF

      ! UPDATE SV COSINE AND TIME TAG ARRAYS
      ! (TO BE USED DURING BACKWARDS RUN)

      IF ((NIGHT.AND.(SVBCOS.LT.CNIGHT)) .OR. (NOON.AND.(SVBCOS.GT.CNOON))) THEN
        DTTAG=DABS(TTAG-ECLSTM(NECLIPS))

        ! ECLIPSE TIME IS MORE THAN 2 HOURS, THIS IS A NEW ECLIPSE!

        IF (DTTAG .GT. TWOHR) THEN
          NECLIPS=NECLIPS+1
          ECLSTM(NECLIPS)=TTAG+DET/MURATE
          ! IIR MIDNIGHT/NOON TURN  or II/IIA NOON TURN START AND GLONASS NOON
          IF ((BLK(1:9).EQ.'BLOCK IIR' .OR. TRIM(BLK).EQ.'BLOCK IIIA') .OR. NOON) THEN
            ! GLONASS
            IF (BLK(1:9).EQ.'GLONASS-M' .OR. BLK(1:10).EQ.'GLONASS-K1') THEN
              ! GLONASS NOON TURN MODE ACORDING TO DILSSNER ET AL 2010
              ECLSTM(NECLIPS)=ECLSTM(NECLIPS)-ANOON/MURATE
              ECLETM(NECLIPS)=ECLSTM(NECLIPS)+2.D0*ANOON/MURATE
            ELSE
              ! GPS TURNS ONLY
              ECLSTM(NECLIPS)=ECLSTM(NECLIPS)-DABS(BETADG)*DSQRT(ANOON/DABS(BETADG)-1.d0)/MURATE
              ECLETM(NECLIPS)=ECLSTM(NECLIPS)+2*DABS(BETADG)*DSQRT(ANOON/DABS(BETADG)-1.d0)/MURATE
            END IF
          END IF
          ! II/IIA SHADOW START & END TIMES
          ! GLONASS & IIF AS WELL !
          IF (((TRIM(BLK).EQ.'BLOCK I').OR.(TRIM(BLK).EQ.'BLOCK II').OR.(TRIM(BLK).EQ.'BLOCK IIA').OR. &
             (TRIM(BLK).EQ.'BLOCK IIF').OR.(TRIM(BLK).EQ.'GLONASS-M').OR.(TRIM(BLK).EQ.'GLONASS-K1')) .AND. NIGHT) THEN
            ECLSTM(NECLIPS)=ECLSTM(NECLIPS)-DSQRT((ANIGHT-180.d0)**2-BETADG**2)/MURATE
            ECLETM(NECLIPS)=ECLSTM(NECLIPS)+2.d0*DSQRT((ANIGHT-180.d0)**2-BETADG**2)/MURATE
          END IF
        END IF
      END IF
    ! END OF FORWARD LOOP (IDIR = 1)
    END IF
  END IF

  ! BOTH FWD (IDIR= 1) OR BWD (IDIR=-1)
  ! SET ECLIPSE FLAG (1=NIGHT SHADOW, 2=NOON TURN)

  IF (NECLIPS .NE. 0 ) THEN
    ! CHECK IF IPRN IS ECLIPSING AND WHICH SEQ NO (I)
    I=0
    DO J=1, NECLIPS
      IF (TTAG.GE.ECLSTM(J) .AND. TTAG.LE.(ECLETM(J)+HALFHR)) I=J
    END DO
    ! CURRENTLY NOT ECLIPSING (i=0)
    IF (I .EQ. 0) GOTO 1
    IF (TTAG.GE.ECLSTM(I) .AND. TTAG.LE.(ECLETM(I)+HALFHR)) THEN
      ! velocity & radius unit vectors V & R
      DO J=1,3
        V(J)=VSVC(J)/DSQRT(VSVC(1)**2+VSVC(2)**2+VSVC(3)**2)
        R(J)=XSV(J)/DSQRT(XSV(1)**2+XSV(2)**2+XSV(3)**2)
      END DO
      ! ORBIT ANGLE MU AT ECLIPSE/TURN START
      DET=MURATE*(ECLETM(I)-ECLSTM(I))/2.d0

      ! Dec 12, 2013 - start
      ! YAWEND HERE - IIF SHADOW YAW RATE
      YAWEND=(DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(DET*DEG2RAD))-DATAN2(-DTAN(BETADG*DEG2RAD), DSIN(-DET*DEG2RAD)))/ &
              DEG2RAD/(ECLETM(I)-ECLSTM(I))
      ! Dec 12, 2013 - end

      ! SHADOW CROSSING
      IF (SVBCOS .LT. 0) THEN
        ! BLK IIA/IIF SHADOW CROSSING
        IF ((TRIM(BLK).EQ.'BLOCK I') .OR. (TRIM(BLK).EQ.'BLOCK II') .OR. (TRIM(BLK).EQ.'BLOCK IIA') .OR. &
            (TRIM(BLK).EQ.'BLOCK IIF')) THEN
          IF (TTAG .LE. ECLETM(I)) THEN
            ! IIA NIGHT TURN
            IF ((TRIM(BLK).EQ.'BLOCK I') .OR. (TRIM(BLK).EQ.'BLOCK II') .OR. (TRIM(BLK).EQ.'BLOCK IIA')) &
                                   PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG+ &
                                   SIGN(YRATE,YBIAS)*(TTAG-ECLSTM(I))
                                   !SIGN(YRATE,0.5D0)*(TTAG-ECLSTM(I))
            ! IIF NIGHT TURN (DILSSNER  2010)
            IF (TRIM(BLK).EQ.'BLOCK IIF') PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG+ &
                                   ! Dec 12, 2013- start
                                   ! Correct IIF  NIGHT CROSSING USING COMPUTING YAW RATE (YAWEND)
                                   ! ACCORDING TO THE USAF IIF DOCUMENT
                                   ! SIGN(0.06D0 BETADG)*(TTAG-ECLSTM(I))
                                   YAWEND*(TTAG-ECLSTM(I))
                                   ! Dec 12, 2013 - end
          ELSE
            ! **** WARNING
            ! IIA/IIF SHADOW EXIT RECOVERY: USING THE IIA DATA  DURING
            ! THE IIA RECOVERY (UP TO 30 MIN) IS NOT RECOMMENDED!
            ! **** WARNING
            ! GPS IIA  AT SHADOW EXIT
            IF ((TRIM(BLK).EQ.'BLOCK I') .OR. (TRIM(BLK).EQ.'BLOCK II') .OR. (TRIM(BLK).EQ.'BLOCK IIA')) &
                                   PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG+ &
                                   SIGN(YRATE,YBIAS)*(ECLETM(I)-ECLSTM(I))
                                   !SIGN(YRATE,0.5d0)*(ECLETM(I)-ECLSTM(I))
            ! GPS IIF AT SHADOW EXIT
            IF (TRIM(BLK).EQ.'BLOCK IIF') GOTO 1
            !IF (TRIM(BLK).EQ.'BLOCK IIF') PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG+ &
            !                     SIGN(0.06D0,BETADG)*(ECLETM(I)-ECLSTM(I))
            ! YAWEND- HERE THE ACTUAL  YAW  AT THE SHADOW EXIT
            YAWEND=YANGLE-PHI
            YAWEND=DMOD(YAWEND, 360.D0)
            IF (DABS(YAWEND) .GT. 180.D0) YAWEND= YAWEND-360.D0*YAWEND/DABS(YAWEND)
            PHI=PHI+SIGN(YRATE,YAWEND)*(TTAG-ECLETM(I))
            ! SANTX- THE CURRENT ANGLE DIFF, CONSISTENT WITH YAWEND
            SANTX=YANGLE-PHI
            SANTX=DMOD(SANTX, 360.D0)
            IF (DABS(SANTX) .GT. 180.D0) SANTX=SANTX-360.D0*SANTX/DABS(SANTX)
            ! STOP! THE NOMINAL YAW (YANGLE) REACHED!
            IF (DABS(SANTX) .GT. DABS(YAWEND)) GOTO 1
            IF (YAWEND.NE.0.D0 .AND. ((SANTX)/YAWEND).LT.0.D0) GOTO 1
            ! SET PHI <-180,+180>
            PHI=DMOD(PHI, 360.D0)
            IF (DABS(PHI) .GT. 180.D0) PHI=PHI-360.D0*PHI/DABS(PHI)
          END IF
        END IF

        ! GLONASS
        IF (BLK(1:9).EQ.'GLONASS-M' .OR. BLK(1:10).EQ.'GLONASS-K1') THEN
          ! GLONASS/GPS  NIGHT TURN (DILSSNER AT AL 2010 )
          IF (TTAG .GT. ECLETM(I)) GOTO 1
          YAWEND=YRATE
          PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG+SIGN(YAWEND,BETADG)*(TTAG-ECLSTM(I))
          ! YAWEND -YAW ANGLE AT THE (GLONASS) SHADOW EXIT
          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN( DET*DEG2RAD))*RAD2DEG
          IF ((YAWEND/PHI).GE.1.d0 .OR. (PHI/YAWEND).LT.0.d0) THEN
            PHI=YAWEND
          END IF
        END IF

        ! Dec 12, 2013
        ! GPS BLK IIF NIGHT YAW RATE(DILSSNER 2010):
        ! IF (BLK(1:9) .EQ. 'BLOCK IIF') THEN
        !  IF (DABS(BETADG).GT.8.D0) GO TO 1
        ! END IF

        ! BLK II R SHADOW (MIDNIGHT TURN) CROSSING
        IF (BLK(1:9).EQ.'BLOCK IIR' .OR. TRIM(BLK).EQ.'BLOCK IIIA') THEN
          PHI=DATAN2(DTAN(BETADG*DEG2RAD),-DSIN(-DET*DEG2RAD))*RAD2DEG+SIGN(YRATE,BETADG)*(TTAG-ECLSTM(I))
          IF((PHI/YANGLE).GE.1.d0.OR.(PHI/YANGLE).LT.0.d0) GO TO 1
        END IF
        ! write(*,*)"R",IPRN-32,TTAG,YANGLE, PHI,DET, BETADG, ECLETM(IPRN,I),I
        IECLIPS=1
      ELSE
        ! NOON TURNS
        PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI-DET*DEG2RAD))*RAD2DEG-SIGN(YRATE,BETADG)*(TTAG-ECLSTM(I))

        ! Dec 12, 2013 -start
        ! SMALL NEGATIVE BETA IIF OR SMALL POSIT. IIA NOON TURN PROBLEM
        ! Jan 24, 2014
        !               IF((IBLK(IPRN).LE.3.OR.IBLK(IPRN).EQ.6).AND.
        IF (CPRN(1:1).EQ.'G' .AND. &
        ! CHANGE THE EMPIRICAL BETA LIMIT 0.9 DEG, IF REQ'D
            (BETADG*SIGN(1.D0,YBIAS)).LE.0.9D0  .AND. &
        ! IN THEORY THE ABOVE LIMIT OF 0.9 DEG SHOULD BE ABS(YBIAS)!
            (BETADG*YBIAS).GT.0.0D0) THEN
          PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI-DET*DEG2RAD))*RAD2DEG+SIGN(YRATE,YBIAS)*(TTAG-ECLSTM(I))
        END IF
        ! Dec 12, 2013 - end

        ! BLK IIR NOON TURNS ONLY
        IF (BLK(1:9).EQ.'BLOCK IIR' .OR. TRIM(BLK).EQ.'BLOCK IIIA') THEN
          PHI=DATAN2(DTAN(BETADG*DEG2RAD),-DSIN(PI-DET*DEG2RAD))*RAD2DEG-SIGN(YRATE,BETADG)*(TTAG-ECLSTM(I))
          ! IIR END TURN CHECK
          IF ((YANGLE/PHI).GE.1.d0 .OR. (PHI/YANGLE).LT.0.d0) GOTO 1
        ELSE
          ! GLONASS END TURN CHECK
          IF ((BLK(1:9).EQ.'GLONASS-M' .OR. BLK(1:10).EQ.'GLONASS-K1') .AND. TTAG.GT.ECLETM(I)) GOTO 1
          ! IIA OR IIF END TURN CHECK
          ! Dec 12, 2013 -start
          IF (CPRN(1:1).EQ.'G' .AND. BETADG*SIGN(1.D0,YBIAS).LE.0.9D0 .AND. &
          ! Jan 24, 2014
          !    &             BETADG*SIGN(1.D0,YBIAS).GT.0.0D0.AND.
              BETADG*YBIAS.GT.0.0D0 .AND. &
              (((PHI-SIGN(1.d0,YBIAS)*360.D0)/YANGLE).LE.1.d0 .OR. &
               ((PHI-SIGN(1.D0,YBIAS)*360.D0)/YANGLE).LT.0.d0)) GOTO 1
          ! IF(IPRN.LE.32.AND.
          IF (CPRN(1:1).EQ.'G' .AND. (BETADG*SIGN(1.D0,YBIAS).GT.0.9D0 .OR. &
          ! Jan 24, 2014
          !    &              BETADG*SIGN(1.D0,YBIAS).LE.0.0D0).AND.
              BETADG*YBIAS.LE.0.0D0) .AND. &
              ((PHI/YANGLE).GE.1.d0 .OR. (PHI/YANGLE).LT.0.d0)) GOTO 1

          !IF (((TRIM(BLK).EQ.'BLOCK I').OR.(TRIM(BLK).EQ.'BLOCK II').OR.(TRIM(BLK).EQ.'BLOCK IIA').OR. &
          !    (TRIM(BLK).EQ.'BLOCK IIF')) .AND. ((PHI/YANGLE).GE.1.d0.OR.(PHI/YANGLE).LT.0.d0)) GOTO 1

        END IF
        ! write(*,*)"S",IPRN-32,TTAG,YANGLE, PHI,DET, BETADG, ECLSTM(IPRN,I)
        IECLIPS=2
      END IF

      ! ROTATE X-VECTOR TO ECLIPSING YAW ANGLE PHI
      ! ECLIPSING (II/IIA) NOT TO BE USED  A HALF HR AFTER SHADOW !
      SANTX=(DCOS((PHI-YANGLE)*DEG2RAD)*(V(2)-V(3)*R(2)/R(3))-DCOS(PHI*DEG2RAD)* &
            (SANTXYZ(2)-SANTXYZ(3)*R(2)/R(3)))/(SANTXYZ(1)*V(2)-SANTXYZ(2)*v(1)+ &
            ((SANTXYZ(2)*V(3)-SANTXYZ(3)*V(2))*R(1)+(SANTXYZ(3)*V(1)- &
            SANTXYZ(1)*V(3))*R(2))/R(3))
      SANTY=(DCOS(PHI*DEG2RAD) - (V(1)-V(3)*R(1)/R(3))*SANTX)/(V(2)-V(3)*R(2)/R(3))
      ! THE BODY-X UNIT VECTOR ROTATED BY (PHI-YANGLE) RETURNED
      SANTXYZ(1)=SANTX
      SANTXYZ(2)=SANTY
      SANTXYZ(3)=(-R(1)*SANTX-R(2)*SANTY)/R(3)
    END IF
  END IF

1 RETURN

END SUBROUTINE




SUBROUTINE ECLIPS2( IDIR, TTAG, CPRN, BLK, YRATE, SVBCOS, ANIGHT, &
                   IECLIPS, NECLIPS, ECLSTM, ECLETM, &
                   XSV, SANTXYZ, VSVC, BETA, YANGLE, PHI)
!
!       NAME            ECLIPS (version Dec  2013)
!
!     PURPOSE   DETECT ECLIPSING & YAW ROTATE ECLIP. SATELLITES
!                       (THE INPUT BODY-X UNIT VECTOR - SANTXYZ IS YAW-ROTATED
!                        BY PHI-YANGLE (THE ECL-NOMINAL) YAW ANGLE DIFFERENCE)
!
!       COPYRIGHT       GEODETIC SURVEY DIVISION, 2011.
!                       ALL RIGHTS RESERVED.
!                       ALL TERMS AND CONDITIONS APPLY AS DETAILED IN
!                       " TERMS AND CONDITIONS FOR SOFTWARE "
!
!       CONTACT         kouba@geod.nrcan.gc.ca
!
!       UPDATE HISTORY: Aug. 23, 2011:1996-2008 W. AVERAGES of JPL REPROCESSING
!                                YRATE SOLUTIONS FOR ALL II/IIA CODED IN DATA
!                                STATEMENT, THIS ENABLES REPROCESSING FROM 1996
!                       Sep 26, 2011: 1. Corrected bug causing Block IIF shadow
!                               CROSSING MANEVURE WITH 0.06 DEG/SEC RATE EVEN
!                               FOR BETADG > 8 DEG
!                                     2. CORRECTED/improved IIA RECOVERY logic
! Dec 12, 2013 - start
!                       Dec 18, 2013: 1.corrected IIF night turns (USAF Doc.)
!                                     2.small neg beta IIF and small pos IIA noon turn
!                                    (wrong) directions  for |beta| < 0.9deg
!                                     3. PRN/SVN 23 IIA YBIAS= -0.5 deg up to Feb 2004
!                                     4. All the above changes labeled "C Dec 12, 2013"
! Dec 12, 2013 - end
!
!                      Jan 24, 2014:  NOON RECOVERY CORRECTED IF IIA/IIF's HAVE YBIAS=0
!                                    (NOT APPLICABLE CURRENTLY,POSSIBLE FOR FUTURE IIF?)
!                                    & SMALL IIA/IIF BETA IF STATEMENT SIMPLIFIED
!
!     PARAMETERS        DESCRIPTION
!
!        IDIR           DIRECTION OF PROCESSING (1=FORWARD, -1=BACKWARD)
!        IPRN           SV PRN NUMBER (.LE.32 FOR GPS, .GT.32 FOR GLONASS)
!        TTAG           OBSERVATION EPOCH TIME TAG (EG SEC OF GPS WEEK)
!        SVBCOS         SV BETA ANGLE (BETWEEN SV AND SUN RADIUS) COSINE
!        ANOON          SV BETA ANGLE LIMIT (DEG) FOR A NOON TURN MANEVURE
!        ANIGHT         SV BETA ANGLE LIMIT (DEG) FOR A NIGHT SHADOW CROSSING
!        NECLIPS        NUMBER OF ECLIPSING FOR THE PRN SATELLITE
!        ECLSTM         ECLIPSE START TIME(EG SEC OF GPS WEEK)
!        ECLETM         ECLIPSE END TIME  ( "         "      )
!        IECLIPS        SV ECLIPSING (0=NO,1, 2=YES(1=night, 2=noon))
!        PI             = PI=3.1415926536D0
!        XSV(3)         SV X, Y, Z (m)(ITRF)
!        SANTXYZ        BODY-X UNIT VECTOR (ITRF)
!                       WARNING: THE IIA BODY-X ORIENTATION EXPECTED FOR THE IIR
!                        THE  BODY-X REVERSED FOR IIR (SEE BELOW) & RETURNED
!        VSVC           SV INERTIAL VELOCIRY VECTOR IN ITRF
!        BETA           90 DEG + THE SUN ANGLE WITH ORBITAL PLANE(IN RAD)
!        IBLK           SV BLOCK  1=I, 2=II, 3=IIA, IIR=(4, 5) IIF=6
!
!        INTERNAL PARAMETRS DESCRIPTION
! Dec 12, 2013
!        YBIAS       IIA YAW BIAS= 0.5 deg SINCE NOV95,EXCEPT PRN/SVN23?
!        YANGLE         THE NOMINAL YAW ANGLE
!        PHI            THE ECLIPSING YAW ANGLE
!
! REMARKS:
! SVBCOS, the COS of the angle between the sv radius vector and the sun
! radius vector, (the dot product of the above respective unit vectors),
! SVBCOS is used to test against CNOON=COS(ANOON), if sv is entering
! a noon maneuverer (i.e., SVBCOS > CNOON). The ANOON limit
! (typically < 5.7 deg), is determined within the subroutine and depends
! on the  sv yaw rate (YRATE)and GNSS (GPS or GLONASS).
!
! ANIGHT , the shadow limit is the "input " in the subroutine
! call statement, it can be hard coded as it is constant for a GNSS type,
! e.g.,
! 180.D0+-13.25D0 for GPS (IPRN.GE. 32) and 180.D0+-14.20D0 for
! GLONASS (IPRN.GT.32), resp.). CNIGHT=COS(ANIGHT) is used for testing.
! When SVBCOS < CNIGHT (CNIGHT is negative and close to -1),
! the SV enters, or it is in the shadow.
!
! *********************************************************************
!
USE const
IMPLICIT NONE

!*
! THE ARGUMENTS
!!-----------------------------
INTEGER(IT) IDIR
INTEGER(IT) IECLIPS, NECLIPS

REAL(RL) TTAG, SVBCOS, YRATE
REAL(RL) ECLSTM(*), ECLETM(*)
REAL(RL) ANIGHT,MU
REAL(RL) XSV(*),SANTXYZ(*),VSVC(*)
REAL(RL) BETA, YANGLE, PHI

CHARACTER(LEN=*) CPRN, BLK


  !*
  ! THE LOCAL VARIABLES
  !!-----------------------------
  REAL(RL) TWOHR, HALFHR
  REAL(RL) CNOON, CNIGHT
  REAL(RL) DTTAG, ANOON
  REAL(RL) MURATE, DET, BETADG
  REAL(RL) SANTX, SANTY, v(3), r(3)
  REAL(RL) YAWEND, YBIAS, SUT(3)
  INTEGER(IT) J, I

  LOGICAL(LG) NOON, NIGHT

  !*
  ! START THE EXECTUABLE CODES
  !!-----------------------------

  ! Dec 12, 2013
  ! YBIAS=-0.5 FOR IIA (IBLK<4) PRN23 (SVN23 UP TO FEB2004,AFTER  IIR SVN60
  ! AND NOT USED), IIF (IBLK=6)=-0.5, USED FOR SMALL NEG BETA NOON TURNS ONLY!
  YBIAS=0.0D0

  IECLIPS=0
  TWOHR =7200.D0
  HALFHR=1800.D0

  ! compute the noon beta angle limit (beta zero) FOR A NOON TURN from YRATEs
  ! THE ACTUAL SAT ORBIT ANGLE RATE (MURATE) (~0.00836 FOR GPS; ~ 0.00888 GLNS)
  MURATE=DSQRT((VSVC(1)**2+VSVC(2)**2+VSVC(3)**2)/(XSV(1)**2+XSV(2)**2+XSV(3)**2))*RAD2DEG

  NOON=.FALSE.
  NIGHT=.FALSE.
  BETADG=BETA*RAD2DEG-90.d0

  MU=SVBCOS/DCOS(BETADG*DEG2RAD)

  SELECT CASE(TRIM(BLK))
    CASE('GALILEO-1')
      ANOON=15.d0
      IF (MU.LT.DCOS((180.d0+15.d0)*DEG2RAD) .AND. DABS(BETADG).LE.2.0d0) THEN
        NIGHT=.TRUE.
      END IF
      IF (MU.GT.DCOS(15.d0*DEG2RAD) .AND. DABS(BETADG).LE.2.0d0) THEN
        NOON=.TRUE.
      END IF
    CASE('GALILEO-2')
      ANOON=10.d0
      IF (MU.LT.DCOS((180.d0+10.d0)*DEG2RAD) .AND. DABS(BETADG).LE.4.1d0) THEN
        NIGHT=.TRUE.
      END IF
      IF (MU.GT.DCOS(10.d0*DEG2RAD) .AND. DABS(BETADG).LE.4.1d0) THEN
        NOON=.TRUE.
      END IF
    CASE('BEIDOU-2I','BEIDOU-2M', &
         'BEIDOU-3I-SECM','BEIDOU-3I-CAST','BEIDOU-3M-SECM','BEIDOU-3M-CAST', &
         'BEIDOU-3IS-SECM','BEIDOU-3IS-CAST','BEIDOU-3MS-SECM','BEIDOU-3MS-CAST', &
         'BEIDOU-3SI-SECM','BEIDOU-3SI-CAST','BEIDOU-3SM-SECM','BEIDOU-3SM-CAST')
      ANOON=6.d0
      IF (MU.LT.DCOS((180.d0+6.d0)*DEG2RAD) .AND. DABS(BETADG).LE.3.d0) THEN
        NIGHT=.TRUE.
      END IF
      IF (MU.GT.DCOS(6.d0*DEG2RAD) .AND. DABS(BETADG).LE.3.d0) THEN
        NOON=.TRUE.
      END IF
    CASE DEFAULT
      RETURN
  END SELECT

  ! IF SV IN NIGHT SHADOW OR NOON TURN DURING FORWARD PASS
  ! STORE START AND END TIME OF YAW MANEUVRE (FOR THE BACKWARD RUN)

  ! YAW ANLGE
  YANGLE=DACOS((SANTXYZ(1)*VSVC(1)+SANTXYZ(2)*VSVC(2)+SANTXYZ(3)*VSVC(3))/ &
                DSQRT(VSVC(1)**2+VSVC(2)**2+VSVC(3)**2))*RAD2DEG

  IF (BETADG .GT. 0.d0) YANGLE=-YANGLE

  IF (NIGHT .OR. NOON) THEN
    ! the middle of a turn
    DET=DSQRT((180.d0-DACOS(SVBCOS)*RAD2DEG)**2-BETADG**2)
    PHI=PI/2.d0
    ! Check if already after a midnight or noon
    IF (NIGHT) THEN
      IF (DABS(YANGLE) .LT. 90.d0) DET=-DET
      IF (DET .NE. 0.d0) PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG
    END IF

    IF (NOON) THEN
      DET=DSQRT((DACOS(SVBCOS)*RAD2DEG)**2-BETADG**2)
      IF (DABS(YANGLE) .GT. 90.d0) DET=-DET
      IF (DET .NE. 0.d0) PHI=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI-DET*DEG2RAD))*RAD2DEG
    END IF

    ! ONLY FORWARD
    IF (IDIR .GT. 0) THEN

      ! INITIALIZE ECLIPSE START AND TIME TAG ARRAYS

      IF (NECLIPS .EQ. 0) THEN
        NECLIPS=NECLIPS+1
        ECLSTM(NECLIPS)=TTAG+DET/MURATE

        ECLSTM(NECLIPS)=ECLSTM(NECLIPS)-ANOON/MURATE
        ECLETM(NECLIPS)=ECLSTM(NECLIPS)+2.D0*ANOON/MURATE
      END IF

      ! UPDATE SV COSINE AND TIME TAG ARRAYS
      ! (TO BE USED DURING BACKWARDS RUN)

      DTTAG=DABS(TTAG-ECLSTM(NECLIPS))

      ! ECLIPSE TIME IS MORE THAN 2 HOURS, THIS IS A NEW ECLIPSE!
      IF (DTTAG .GT. TWOHR) THEN
        NECLIPS=NECLIPS+1
        ECLSTM(NECLIPS)=TTAG+DET/MURATE
        ECLSTM(NECLIPS)=ECLSTM(NECLIPS)-ANOON/MURATE
        ECLETM(NECLIPS)=ECLSTM(NECLIPS)+2.D0*ANOON/MURATE
      END IF
    ! END OF FORWARD LOOP (IDIR = 1)
    END IF
  END IF

  ! BOTH FWD (IDIR= 1) OR BWD (IDIR=-1)
  ! SET ECLIPSE FLAG (1=NIGHT SHADOW, 2=NOON TURN)

  IF (NECLIPS .NE. 0 ) THEN
    ! CHECK IF IPRN IS ECLIPSING AND WHICH SEQ NO (I)
    I=0
    DO J=1, NECLIPS
      IF (TTAG.GE.ECLSTM(J) .AND. TTAG.LE.ECLETM(J)) I=J
    END DO
    ! CURRENTLY NOT ECLIPSING (i=0)
    IF (I .EQ. 0) GOTO 1
    IF (TTAG.GE.ECLSTM(I) .AND. TTAG.LE.(ECLETM(I))) THEN
      ! velocity & radius unit vectors V & R
      DO J=1,3
        V(J)=VSVC(J)/DSQRT(VSVC(1)**2+VSVC(2)**2+VSVC(3)**2)
        R(J)=XSV(J)/DSQRT(XSV(1)**2+XSV(2)**2+XSV(3)**2)
      END DO
      ! ORBIT ANGLE MU AT ECLIPSE/TURN START
      DET=MURATE*(ECLETM(I)-ECLSTM(I))/2.d0

      ! SHADOW CROSSING
      IF (SVBCOS .LT. 0) THEN

        IF (TRIM(BLK) .EQ. 'GALILEO-1') THEN
          SUT(1)=-DSIN(PI-DET*DEG2RAD)*DCOS(BETADG*DEG2RAD)
          SUT(2)=-DSIN(BETADG*DEG2RAD)
          SUT(3)=-DCOS(PI-DET*DEG2RAD)*DCOS(BETADG*DEG2RAD)

          YAWEND=DATAN2(SUT(2)/DSQRT(1.D0-SUT(3)**2),SUT(1)/DSQRT(1.D0-SUT(3)**2))*RAD2DEG

          DET=(TTAG-ECLSTM(I))*MURATE-ANOON+180.d0
          SUT(1)=-DSIN(DET*DEG2RAD)*DCOS(BETADG*DEG2RAD)
          SUT(2)=-DSIN(BETADG*DEG2RAD)
          SUT(3)=-DCOS(DET*DEG2RAD)*DCOS(BETADG*DEG2RAD)

          SUT(2)=0.5D0*(DSIN(2.d0*DEG2RAD)*SIGN(1.d0,YAWEND)+SUT(2))+0.5d0*(DSIN(2.d0*DEG2RAD)*SIGN(1.d0,YAWEND)-SUT(2))*DCOS(PI*DABS(SUT(1))/DSIN(15.d0*DEG2RAD))
          SUT(3)=DSQRT(1-SUT(1)**2-SUT(2)**2)*SIGN(1.d0,SUT(3))

          PHI=DATAN2(SUT(2)/DSQRT(1.D0-SUT(3)**2),SUT(1)/DSQRT(1.D0-SUT(3)**2))*RAD2DEG
        END IF

        IF (TRIM(BLK) .EQ. 'GALILEO-2') THEN
          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG
          PHI=90.D0*SIGN(1.D0,YAWEND)+(YAWEND-90.D0*SIGN(1.D0,YAWEND))*DCOS(2*PI/5656.D0*(TTAG-ECLSTM(I)))

          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN( DET*DEG2RAD))*RAD2DEG
          IF ((YAWEND/PHI).GE.1.d0 .OR. (PHI/YAWEND).LT.0.d0) THEN
            PHI=YAWEND
          END IF
        END IF

        IF (TRIM(BLK).EQ.'BEIDOU-2I' .OR. TRIM(BLK).EQ.'BEIDOU-3I-SECM'  .OR. TRIM(BLK).EQ.'BEIDOU-3I-CAST' .OR. &
            TRIM(BLK).EQ.'BEIDOU-3IS-SECM'  .OR. TRIM(BLK).EQ.'BEIDOU-3IS-CAST') THEN
          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG
          PHI=90.D0*SIGN(1.D0,YAWEND)+(YAWEND-90.D0*SIGN(1.D0,YAWEND))*DCOS(2*PI/5740.D0*(TTAG-ECLSTM(I)))

          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN( DET*DEG2RAD))*RAD2DEG
          IF ((YAWEND/PHI).GE.1.d0 .OR. (PHI/YAWEND).LT.0.d0) THEN
            PHI=YAWEND
          END IF
        END IF

        IF (TRIM(BLK).EQ.'BEIDOU-2M' .OR. TRIM(BLK).EQ.'BEIDOU-3M-SECM' .OR. TRIM(BLK).EQ.'BEIDOU-3M-CAST' .OR. &
            TRIM(BLK).EQ.'BEIDOU-3MS-SECM' .OR. TRIM(BLK).EQ.'BEIDOU-3MS-CAST' .OR. &
            TRIM(BLK).EQ.'BEIDOU-3SM-SECM' .OR. TRIM(BLK).EQ.'BEIDOU-3SM-CAST') THEN
          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(-DET*DEG2RAD))*RAD2DEG
          PHI=90.D0*SIGN(1.D0,YAWEND)+(YAWEND-90.D0*SIGN(1.D0,YAWEND))*DCOS(2*PI/3090.D0*(TTAG-ECLSTM(I)))

          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN( DET*DEG2RAD))*RAD2DEG
          IF ((YAWEND/PHI).GE.1.d0 .OR. (PHI/YAWEND).LT.0.d0) THEN
            PHI=YAWEND
          END IF
        END IF

        IECLIPS=1
      ELSE

        IF (TRIM(BLK) .EQ. 'GALILEO-1') THEN
          SUT(1)=-DSIN(-DET*DEG2RAD)*DCOS(BETADG*DEG2RAD)
          SUT(2)=-DSIN(BETADG*DEG2RAD)
          SUT(3)=-DCOS(-DET*DEG2RAD)*DCOS(BETADG*DEG2RAD)

          YAWEND=DATAN2(SUT(2)/DSQRT(1.D0-SUT(3)**2),SUT(1)/DSQRT(1.D0-SUT(3)**2))*RAD2DEG

          ! ORBIT ANGLE
          DET=(TTAG-ECLSTM(I))*MURATE-ANOON
          SUT(1)=-DSIN(DET*DEG2RAD)*DCOS(BETADG*DEG2RAD)
          SUT(2)=-DSIN(BETADG*DEG2RAD)
          SUT(3)=-DCOS(DET*DEG2RAD)*DCOS(BETADG*DEG2RAD)

          SUT(2)=0.5D0*(DSIN(2.d0*DEG2RAD)*SIGN(1.d0,YAWEND)+SUT(2))+0.5d0*(DSIN(2.d0*DEG2RAD)*SIGN(1.d0,YAWEND)-SUT(2))*DCOS(PI*DABS(SUT(1))/DSIN(15.d0*DEG2RAD))
          SUT(3)=DSQRT(1-SUT(1)**2-SUT(2)**2)*SIGN(1.d0,SUT(3))

          PHI=DATAN2(SUT(2)/DSQRT(1.D0-SUT(3)**2),SUT(1)/DSQRT(1.D0-SUT(3)**2))*RAD2DEG
        END IF

        IF (TRIM(BLK) .EQ. 'GALILEO-2') THEN
          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI-DET*DEG2RAD))*RAD2DEG
          PHI=90.D0*SIGN(1.D0,YAWEND)+(YAWEND-90.D0*SIGN(1.D0,YAWEND))*DCOS(2*PI/5656.D0*(TTAG-ECLSTM(I)))

          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI+DET*DEG2RAD))*RAD2DEG
          IF ((PHI/YAWEND).GE.1.d0 .OR. (PHI/YAWEND).LT.0.d0) THEN
            PHI=YAWEND
          END IF
        END IF

        IF (TRIM(BLK).EQ.'BEIDOU-2I' .OR. TRIM(BLK).EQ.'BEIDOU-3I-SECM' .OR. TRIM(BLK).EQ.'BEIDOU-3I-CAST' .OR. &
            TRIM(BLK).EQ.'BEIDOU-3IS-SECM' .OR. TRIM(BLK).EQ.'BEIDOU-3IS-CAST') THEN
          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI-DET*DEG2RAD))*RAD2DEG
          PHI=90.D0*SIGN(1.D0,YAWEND)+(YAWEND-90.D0*SIGN(1.D0,YAWEND))*DCOS(2*PI/5740.D0*(TTAG-ECLSTM(I)))

          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI+DET*DEG2RAD))*RAD2DEG
          IF ((PHI/YAWEND).GE.1.d0 .OR. (PHI/YAWEND).LT.0.d0) THEN
            PHI=YAWEND
          END IF
        END IF

        IF (TRIM(BLK).EQ.'BEIDOU-2M' .OR. TRIM(BLK) .EQ. 'BEIDOU-3M-SECM' .OR. TRIM(BLK).EQ.'BEIDOU-3M-CAST' .OR. &
            TRIM(BLK) .EQ. 'BEIDOU-3MS-SECM' .OR. TRIM(BLK).EQ.'BEIDOU-3MS-CAST' .OR. &
            TRIM(BLK) .EQ. 'BEIDOU-3SM-SECM' .OR. TRIM(BLK).EQ.'BEIDOU-3SM-CAST') THEN
          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI-DET*DEG2RAD))*RAD2DEG
          PHI=90.D0*SIGN(1.D0,YAWEND)+(YAWEND-90.D0*SIGN(1.D0,YAWEND))*DCOS(2*PI/3090.D0*(TTAG-ECLSTM(I)))

          YAWEND=DATAN2(-DTAN(BETADG*DEG2RAD),DSIN(PI+DET*DEG2RAD))*RAD2DEG
          IF ((PHI/YAWEND).GE.1.d0 .OR. (PHI/YAWEND).LT.0.d0) THEN
            PHI=YAWEND
          END IF
        END IF

        IECLIPS=2
      END IF

      ! ROTATE X-VECTOR TO ECLIPSING YAW ANGLE PHI
      ! ECLIPSING (II/IIA) NOT TO BE USED  A HALF HR AFTER SHADOW !
      SANTX=(DCOS((PHI-YANGLE)*DEG2RAD)*(V(2)-V(3)*R(2)/R(3))-DCOS(PHI*DEG2RAD)* &
            (SANTXYZ(2)-SANTXYZ(3)*R(2)/R(3)))/(SANTXYZ(1)*V(2)-SANTXYZ(2)*v(1)+ &
            ((SANTXYZ(2)*V(3)-SANTXYZ(3)*V(2))*R(1)+(SANTXYZ(3)*V(1)- &
            SANTXYZ(1)*V(3))*R(2))/R(3))
      SANTY=(DCOS(PHI*DEG2RAD) - (V(1)-V(3)*R(1)/R(3))*SANTX)/(V(2)-V(3)*R(2)/R(3))
      ! THE BODY-X UNIT VECTOR ROTATED BY (PHI-YANGLE) RETURNED
      SANTXYZ(1)=SANTX
      SANTXYZ(2)=SANTY
      SANTXYZ(3)=(-R(1)*SANTX-R(2)*SANTY)/R(3)
    END IF
  END IF

1 RETURN

END SUBROUTINE
