
      INTEGER*4    LFNKBD,LFNPRT,LFNERR,LFN001,LFN002,LFNEPH,LFNOR1,         &
     &             LFNRP1,LFNORB,LFNRPR,LFNPLT,LFNRES,LFNERF,LFNPRF,         &
     &             LFNLOC
      COMMON/LFNUM/LFNKBD,LFNPRT,LFNERR,LFN001,LFN002,LFNEPH,LFNOR1,         &
     &             LFNRP1,LFNORB,LFNRPR,LFNPLT,LFNRES,LFNERF,LFNPRF,         &
     &             LFNLOC
