C*
      SUBROUTINE RADGMS(I,ARC,VORZ,IG,M,S)
CC
CC NAME       :  RADGMS
CC
CC PURPOSE    :  TRANSFORMS AN ANGLE IN RADIANS INTO
CC                (A) SIGN,HOURS,MINUTES,SECONDS     FOR I=0
CC                (B) SIGN,DEG,MIN,SEC (SEXAGESIMAL) FOR I=1
CC                (C) SIGN,DEG,MIN,SEC (CENTESIMAL)  FOR I=2
CC               RADGMS MAY ALSO BE USED WITH            I=3
CC               TO COMPUTE HOURS,MINUTES,SECONDS
CC               OF A DAY-FRACTION. THE SIGN-VARIABLE
CC               VORZ IS MEANINGLESS IN THIS CASE
CC               THE SIGN IS EDITED IN THE VARIABLE VORZ
CC
CC PARAMETERS :  I      : TRANSFORMATION TYPE (SEE ABOVE)     I*4
CC               ARC    : ANGLE IN RADIANS                    R*8
CC               VORZ   : SIGN OF ANGLE:  " " FOR POSITIVE,   CH*1
CC                        "-" FOR NEGATIVE ANGLES
CC               IG,M   : DEGREES(HOURS),MINUTES              I*4
CC               S      : SECONDS                             R*8
CC
CC SR CALLED  :  ---
CC
CC REMARKS    :  ---
CC
CC AUTHOR     :  W.GURTNER
CC
CC VERSION    :  3.4  (JAN 93)
CC
CC CREATED    :  87/11/03 08:45        LAST MODIFIED :  01-MAR-98
CC
CC CHANGES    :  10-AUG-94 : MR: CALL EXITRC
CC               01-MAR-98 : SS: CALL EXITRC REPLACED BY STOP COMMAND
CC
CC COPYRIGHT  :  ASTRONOMICAL INSTITUTE
CC      1987      UNIVERSITY OF BERNE
CC                    SWITZERLAND
CC
C*
      IMPLICIT REAL*8 (A-H,O-Z)
      CHARACTER*1 VORZ
      INCLUDE 'I:COMLFNUM'
      PI=3.1415926535897932D0
      DELTA=1.D-6
      GOTO (1,2,3,4),I+1
      WRITE(LFNERR,11) I
11    FORMAT(/,' *** SR RADGMS: ILLEGAL TRANSFORMATION TYPE',/,
     1                     16X,'TRANS. TYPE:',I2,/)
      STOP
C  H,M,S
1     SEC=DABS(ARC)*4.32D4/PI+DELTA
      SPM=60.D0
      GOTO 5
C  G,M,S
2     SEC=DABS(ARC)*6.48D5/PI+DELTA
      SPM=60.D0
      GOTO 5
C  GRADS
3     SEC=DABS(ARC)*2.D6/PI+DELTA
      SPM=100.D0
      GOTO 5
C  FRACTIONAL PART OF DAY IN H,M,S
4     SEC=DMOD(ARC,1.D0)*86400.D0+DELTA
      SPM=60.D0
C
5     IG=SEC/(SPM*SPM)
      SECNOG=SEC-IG*SPM*SPM
      M=SECNOG/SPM
      S=SECNOG-M*SPM-DELTA
      IF(S.LT.0.D0) S=0.D0
      IF(I.NE.3) THEN
        VORZ=' '
        IF(ARC.LT.0)VORZ='-'
      END IF
      RETURN
      END
